data:                               # в мм
                                    # id маркера
  - [[500.0,  2500.0, 3000.0]]      # 0
  - [[1000.0, 2500.0, 3000.0]]      # 1
  - [[1500.0, 2500.0, 3000.0]]      # 2
  - [[2000.0, 2500.0, 3000.0]]      # 3
  - [[2500.0, 2500.0, 3000.0]]      # 4
  
  - [[500.0,  2000.0, 3000.0]]      # 5
  - [[1000.0, 2000.0, 3000.0]]      # 6
  - [[1500.0, 2000.0, 3000.0]]      # 7
  - [[2000.0, 2000.0, 3000.0]]      # 8
  - [[2500.0, 2000.0, 3000.0]]      # 9
  
  - [[500.0,  1500.0, 3000.0]]      # 10
  - [[1000.0, 1500.0, 3000.0]]      # 11
  - [[1500.0, 1500.0, 3000.0]]      # 12
  - [[2000.0, 1500.0, 3000.0]]      # 13
  - [[2500.0, 1500.0, 3000.0]]      # 14
  
  - [[500.0,  1000.0, 3000.0]]      # 15
  - [[1000.0, 1000.0, 3000.0]]      # 16
  - [[1500.0, 1000.0, 3000.0]]      # 17
  - [[2000.0, 1000.0, 3000.0]]      # 18
  - [[2500.0, 1000.0, 3000.0]]      # 19
  
  - [[500.0,  500.0,  3000.0]]      # 20
  - [[1000.0, 500.0,  3000.0]]      # 21
  - [[1500.0, 500.0,  3000.0]]      # 22
  - [[2000.0, 500.0,  3000.0]]      # 23
  - [[2500.0, 500.0,  3000.0]]      # 24
  